name: Update LeetCode Metrics

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'  # daily at 2 AM UTC

jobs:
  leetcode-metrics:
    runs-on: ubuntu-latest
    steps:
      # Checkout your repo
      - uses: actions/checkout@v3

      # Generate the metrics SVG
      - name: Generate LeetCode Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.leetcode.svg
          token: NOT_NEEDED
          plugin_leetcode: yes
          plugin_leetcode_sections: solved, skills, recent
          plugin_leetcode_limit_skills: 10
          plugin_leetcode_limit_recent: 2

      # Commit and push changes safely
      - name: Commit Metrics
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add metrics.plugin.leetcode.svg
          git commit -m "Update LeetCode metrics" || echo "No changes to commit"
          git push
