name: Update LeetCode Metrics

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'  # daily at 2 AM UTC

jobs:
  leetcode-metrics:
    runs-on: ubuntu-latest
    steps:
      # Checkout your repository
      - uses: actions/checkout@v3

      # Generate the metrics SVG and commit it directly
      - name: Generate and Commit LeetCode Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.leetcode.svg
          token: NOT_NEEDED
          plugin_leetcode: yes
          plugin_leetcode_sections: solved, skills, recent
          plugin_leetcode_limit_skills: 10
          plugin_leetcode_limit_recent: 2
          output-action: commit
